name: Release

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Build and publish
        uses: gradle/gradle-build-action@v2
        env:
          KRYLEX_REPOSITORY_USERNAME: ${{ secrets.KRYLEX_REPOSITORY_USERNAME }}
          KRYLEX_REPOSITORY_PASSWORD: ${{ secrets.KRYLEX_REPOSITORY_PASSWORD }}
        with:
          arguments: publish

  deploy-dokka:
    runs-on: ubuntu-latest

    needs:
      - publish

    steps:
      - name: Checkout
        uses: actions/chekout@v3

      - name: Build Dokka html
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dokkaHtml

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/dokka/html
          clean: true