name: Release

on:
  push:
    tags:
      - '**'

jobs:
  publish:
    if: "! contains(toJSON(github.event.commits.*.message), '[no ci]')"

    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          java-verion: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish